{% set version = "2016_04_27" %}

package:
  name: halide
  version: {{ version }}

source:
  git_url: https://github.com/Halide/halide.git
  git_tag: release_{{ version }}

build:
  number: 0
  skip: True    # [win]

requirements:
 build:
        - gcc     # [osx]
        - llvm
        - cmake
    run:
        - libgcc  # [osx]

  run:
    - python

#test:
#  imports:
#    - example
#  commands:
#    - python -c "import example;"

about:
  home: https://github.com/halide/Halide
  license: BSD
  summary: A language for image processing and computational photography

extra:
  recipe-maintainers:
    - arokem
